// The internal design skill is documentation, so nothing it says fails at
// runtime when it goes wrong. These tests cover the three ways it can go wrong
// silently: a generated file drifting from the token source, the adherence
// lint's rules being pinned to families the system no longer uses, and the
// brand mark drifting away from the favicon it is supposed to be.
import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import test from "node:test";

import { LUXE_FAVICON_SVG, MARK_FIELD, MARK_INK } from "../src/luxe-brand.js";

const SKILL = new URL("../.agents/skills/luxe-design/", import.meta.url);

const read = (path) => readFile(new URL(path, SKILL), "utf8");
const tokensSource = readFile(new URL("../src/luxe-tokens.css", import.meta.url), "utf8");

async function token(name) {
  const match = new RegExp(`--${name}\\s*:\\s*([^;]+);`).exec(await tokensSource);
  assert.ok(match, `token --${name} is missing from luxe-tokens.css`);
  return match[1].trim();
}

// The skill directory is not served by any route, so it cannot import the
// product's stylesheet - it has to carry a copy. Generating that copy is the
// only thing keeping the two the same file.
test("the skill's tokens.css is the product token block verbatim", async () => {
  const source = await tokensSource;
  const copy = await read("tokens.css");

  assert.ok(copy.includes(source.slice(source.indexOf(":root {"))), "tokens.css is not a verbatim copy");
  assert.match(copy, /GENERATED by scripts\/build-design-skill\.js/);
});

// Upstream's lint named its three font families inline, so it rejected the
// system it was meant to protect the moment the families changed. Deriving them
// is what stops that recurring.
test("the adherence rules are derived from the tokens, not hardcoded", async () => {
  const manifest = JSON.parse(await read("adherence.json"));

  assert.equal(manifest.families.sans, /"([^"]+)"/.exec(await token("font-sans"))[1]);
  assert.equal(manifest.families.mono, /"([^"]+)"/.exec(await token("font-mono"))[1]);

  assert.deepEqual(manifest.fontSizes, {
    "--text-heading": await token("text-heading"),
    "--text-body": await token("text-body"),
    "--text-control": await token("text-control"),
    "--text-label": await token("text-label"),
  });
  assert.deepEqual(manifest.fontWeights, {
    "--weight-regular": await token("weight-regular"),
    "--weight-medium": await token("weight-medium"),
  });
  assert.equal(Object.keys(manifest.radii).length, 6);

  // Four sizes and two weights is the rule, not an accident of the current file.
  assert.equal(Object.keys(manifest.fontSizes).length, 4);
  assert.equal(Object.keys(manifest.fontWeights).length, 2);

  // Every token in the file is inventoried, each with a value and a kind.
  const declared = (await tokensSource).match(/^\s*--[a-z0-9-]+\s*:/gim) ?? [];
  assert.equal(manifest.tokens.length, declared.length);
  for (const entry of manifest.tokens) {
    assert.ok(entry.name.startsWith("--"), `${entry.name} is not a custom property`);
    assert.ok(entry.value.length > 0, `${entry.name} has no value`);
    assert.notEqual(entry.kind, "other", `${entry.name} could not be classified`);
  }
});

// The mark and the favicon are one drawing shipped through two mechanisms.
// Neither can read a custom property, so both hold literals, and a change to
// one is silent in the other.
test("the brand mark is the favicon artwork", async () => {
  const mark = await read("assets/luxe-mark.svg");
  const wordmark = await read("assets/luxe-wordmark.svg");
  // The favicon is a data URI, so it is written with single quotes.
  const path = /d='([^']+)'/.exec(LUXE_FAVICON_SVG)[1];

  for (const [name, artwork] of [
    ["mark", mark],
    ["wordmark", wordmark],
  ]) {
    assert.ok(artwork.includes(path), `${name} does not carry the favicon's letterform`);
    assert.ok(artwork.includes(MARK_FIELD), `${name} does not use the favicon's field colour`);
    assert.ok(artwork.includes(MARK_INK), `${name} does not use the favicon's ink colour`);
  }

  // And those two literals are still token values, which is what the favicon
  // mirrors in the first place.
  assert.equal(MARK_FIELD, await token("dark-fill"));
  assert.equal(MARK_INK, await token("canvas"));

  // Upstream's wordmark carried CSS classes with no stylesheet behind them, so
  // it rendered as flat black text wherever it was used.
  assert.doesNotMatch(wordmark, /class=/);

  // An SVG is XML, and an XML comment may not contain a double hyphen. Writing
  // token names with their leading dashes in a header comment makes the whole
  // file fail to parse, and the only symptom is a broken-image icon.
  for (const [name, artwork] of [
    ["mark", mark],
    ["wordmark", wordmark],
  ]) {
    for (const comment of artwork.match(/<!--[\s\S]*?-->/g) ?? []) {
      assert.doesNotMatch(comment.slice(4, -3), /--/, `${name} has a comment XML cannot parse`);
    }
  }
});

test("the adherence lint applies brand exemptions to Windows-style paths", async () => {
  const { lintSource } = await import("../scripts/check-design-adherence.js");
  const mark = await read("assets/luxe-mark.svg");

  assert.deepEqual(lintSource(".agents\\skills\\luxe-design\\assets\\luxe-mark.svg", mark), []);
});

test("every preview card is a specimen card that links the shared shell", async () => {
  const cards = (await readdir(new URL("preview/", SKILL))).filter((file) => file.endsWith(".html"));

  assert.ok(cards.length >= 20, `expected the full card set, found ${cards.length}`);
  for (const card of cards) {
    const source = await read(`preview/${card}`);
    assert.match(source, /<!-- @dsCard group="[^"]+" name="[^"]+" subtitle="[^"]+" viewport="\d+x\d+" -->/, card);
    assert.match(source, /href="_base\.css"/, card);
    // One doctype, one card: a stray second doctype means a copy-paste slip.
    assert.equal((source.match(/<!doctype/gi) ?? []).length, 1, card);
  }
});

// Decision D9: the generated bundle, the hand-maintained manifest, the rendered
// thumbnail and the JSX kit are gone, and no generator exists to bring them
// back. A file reappearing here means someone copied it from upstream.
test("the skill ships no generated artifact it cannot regenerate", async () => {
  const entries = await readdir(SKILL, { recursive: true });

  for (const entry of entries) {
    assert.doesNotMatch(entry, /^_ds_|\.thumbnail$|^ui_kits/, `${entry} was deleted by D9 and must stay deleted`);
    assert.doesNotMatch(entry, /\.jsx$/, `${entry} is a UI-kit component and the kit was deleted`);
  }
});
